spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    username: postgres
    password: postgres
    url: "jdbc:postgresql://localhost:6432/task_tracker_db"
    driver-class-name: "org.postgresql.Driver"